import {useRef,useState} from 'react'
import {AlertTriangle,CheckCircle2,Cloud,Download,FileJson,RotateCcw,ShieldCheck,Upload,X} from 'lucide-react'
import type {CloudController,MigrationResult,OperationalData} from './lib/cloudData'

export const BACKUP_SCHEMA_VERSION=1
export const APP_DATA_KEY='jst-command-center-v1'
export const LAST_BACKUP_KEY='jst-command-center-last-backup'
type Backup={app:string;schemaVersion:number;appVersion:string;exportedAt:string;data:OperationalData}

const dateLabel=(value:string)=>value?new Date(value).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'}):'Never'
const counts=(data:OperationalData)=>({Songs:data.songs?.length||0,Shows:data.shows?.length||0,Rehearsals:data.rehearsals?.length||0,Releases:data.releases?.length||0,Content:data.content?.length||0,Tasks:data.tasks?.length||0})
const nestedCounts=(data:OperationalData)=>({SetlistSongs:data.shows.reduce((n,s)=>n+(s.setlist?.length||0),0),ChecklistItems:data.shows.reduce((n,s)=>n+(s.checklistV2||[]).reduce((m:number,c:any)=>m+(c.items?.length||0),0),0),MerchItems:data.shows.reduce((n,s)=>n+(s.merch?.length||0),0),Recaps:data.shows.filter(s=>s.recap).length,Milestones:data.releases.reduce((n,r)=>n+(r.milestones?.length||0),0),RehearsalSongs:data.rehearsals.reduce((n,r)=>n+(r.songs?.length||0),0)})
export const makeBackup=(data:OperationalData):Backup=>({app:'JST Command Center',schemaVersion:BACKUP_SCHEMA_VERSION,appVersion:'1.0.0',exportedAt:new Date().toISOString(),data})
export const migrateBackup=(backup:Backup)=>{if(backup.schemaVersion>BACKUP_SCHEMA_VERSION)throw new Error('This backup was created by a newer version of JST Command Center.');const data=backup.data;return {...data,rehearsals:data.rehearsals||[],shows:data.shows||[],releases:data.releases||[],songs:data.songs||[],content:data.content||[],tasks:data.tasks||[]}}
export const validateBackup=(value:any):Backup=>{if(!value||typeof value!=='object')throw new Error('The selected file does not contain a valid backup.');if(value.app!=='JST Command Center')throw new Error('This file is not a JST Command Center backup.');if(!Number.isInteger(value.schemaVersion)||!value.exportedAt||!value.data)throw new Error('This JST backup is missing required metadata.');for(const key of ['shows','rehearsals','releases','songs','content','tasks'])if(!Array.isArray(value.data[key]))throw new Error(`The backup is missing a valid ${key} collection.`);migrateBackup(value);return value}
export const downloadBackup=(data:OperationalData)=>{const backup=makeBackup(data),day=backup.exportedAt.slice(0,10),blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`JST-Command-Center-Backup-${day}.json`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return backup.exportedAt}

export default function DataBackup({data,cloud,onRestore,onReset}:{data:OperationalData;cloud:CloudController;onRestore:(data:OperationalData)=>void;onReset:()=>void}){
 const input=useRef<HTMLInputElement>(null)
 const [last,setLast]=useState(()=>localStorage.getItem(LAST_BACKUP_KEY)||''),[pending,setPending]=useState<Backup|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[resetOpen,setResetOpen]=useState(false),[resetText,setResetText]=useState(''),[migrationOpen,setMigrationOpen]=useState(false),[migrationConfirmed,setMigrationConfirmed]=useState(false),[migrationResult,setMigrationResult]=useState<MigrationResult|null>(null)
 const exportNow=()=>{const at=downloadBackup(data);localStorage.setItem(LAST_BACKUP_KEY,at);setLast(at);setSuccess('BACKUP EXPORTED');setError('')}
 const read=async(file?:File)=>{if(!file)return;setError('');setSuccess('');try{const parsed=JSON.parse(await file.text()),backup=validateBackup(parsed);setPending(backup)}catch(cause){setPending(null);setError(cause instanceof Error?cause.message:'Could not read this backup file.')}finally{if(input.current)input.current.value=''}}
 const restore=()=>{if(!pending)return;try{onRestore(migrateBackup(pending));setPending(null);setSuccess(cloud.migrationComplete?'BACKUP RESTORED · CHANGES QUEUED FOR CLOUD SYNC':'BACKUP RESTORED');setError('')}catch(cause){setError(cause instanceof Error?cause.message:'The backup could not be restored.')}}
 const reset=()=>{if(resetText!=='RESET')return;onReset();setResetOpen(false);setResetText('');setSuccess(cloud.migrationComplete?'LOCAL CACHE CLEARED · CLOUD DATA RELOADED':'APP DATA RESET');setLast('')}
 const migrate=async()=>{if(!last||!migrationConfirmed)return;setError('');setSuccess('');try{const result=await cloud.migrate(data);setMigrationResult(result);setMigrationOpen(false);setSuccess('CLOUD MIGRATION COMPLETE · COUNTS AND SAMPLE FIELDS VERIFIED')}catch(cause){setError(cause instanceof Error?cause.message:'Cloud migration failed. Local data remains untouched.')}}
 return <div className="dataPage">
  <section className="dataHero"><ShieldCheck/><div><span className="eyebrow">DATA PROTECTION &amp; CLOUD SYNC</span><h2>DATA &amp; BACKUP</h2><p>Your local snapshot remains available while shared JST records sync through Supabase.</p></div></section>
  {success&&<div className="dataNotice success"><CheckCircle2/>{success}</div>}{error&&<div className="dataNotice error"><AlertTriangle/><div><b>DATA ERROR</b><span>{error}</span></div><button className="icon" onClick={()=>setError('')}><X/></button></div>}
  <section className="cloudDataPanel record"><div className="cloudDataHead"><Cloud/><div><span className="eyebrow">SHARED WORKSPACE</span><h3>Cloud Data</h3></div><b className={`syncState ${cloud.phase}`}>{cloud.message}</b></div><dl><div><dt>WORKSPACE</dt><dd>JumpStart Tomorrow</dd></div><div><dt>LAST SUCCESSFUL SYNC</dt><dd>{dateLabel(cloud.lastSync)}</dd></div><div><dt>PENDING OFFLINE CHANGES</dt><dd>{cloud.pendingCount}</dd></div><div><dt>MIGRATION</dt><dd>{cloud.migrationComplete?'Cloud migration complete':'Local data awaiting migration'}</dd></div></dl>{!cloud.migrationComplete&&<><p className="migrationWarning"><AlertTriangle/><b>Your local data will remain untouched until cloud migration is verified.</b></p><button className="primary" onClick={()=>setMigrationOpen(true)}><Cloud/> Migrate Local Data to Cloud</button></>}{cloud.migrationComplete&&<button className="ghost" onClick={()=>void cloud.reload()} disabled={cloud.phase==='syncing'}>Refresh Cloud Data</button>}
  {migrationResult&&<div className="migrationResults"><b>LAST MIGRATION RESULT</b>{Object.entries(migrationResult.sections).map(([name,result])=><span key={name}>{name}: {result.inserted} inserted · {result.updated} updated · {result.skipped} skipped · {result.failed} failed</span>)}</div>}</section>
  <div className="dataActions"><article className="record"><Download/><span className="eyebrow">SAVE A COPY</span><h3>Export Backup</h3><p>Downloads every show, checklist, rehearsal, release timeline, song, content item, task, recap, merch count, and note.</p><button className="primary" onClick={exportNow}><Download/> Export Backup</button><small>{last?`Last backup: ${dateLabel(last)}`:'No backup yet'}</small></article><article className="record"><Upload/><span className="eyebrow">BRING DATA BACK</span><h3>Import Backup</h3><p>Select a JST JSON backup. Nothing is replaced until the backup passes validation and you confirm it.</p><input ref={input} hidden type="file" accept="application/json,.json" onChange={event=>read(event.target.files?.[0])}/><button className="ghost" onClick={()=>input.current?.click()}><FileJson/> Choose Backup File</button><small>{cloud.migrationComplete?'Restored records will sync to the shared workspace.':'Works with the normal file picker on desktop and mobile.'}</small></article></div>
  <section className="dangerZone"><div><span className="eyebrow">{cloud.migrationComplete?'DEVICE CACHE':'DANGER ZONE'}</span><h3>{cloud.migrationComplete?'Reload Local Cache':'Reset App Data'}</h3><p>{cloud.migrationComplete?'Clear this device snapshot and reload verified cloud data.':'Return JST Command Center to its clean starting data on this device.'}</p></div><button className="dangerButton" onClick={()=>setResetOpen(true)}><RotateCcw/> {cloud.migrationComplete?'Reload Cache':'Reset App Data'}</button></section>
  {migrationOpen&&<div className="scrim"><div className="modal migrationConfirm"><div className="modalHead"><div><span className="eyebrow">ONE-TIME CLOUD MIGRATION</span><h2>MIGRATION PREVIEW</h2></div><button className="icon" onClick={()=>setMigrationOpen(false)}><X/></button></div><div className="backupCounts">{Object.entries(counts(data)).map(([name,total])=><span key={name}><b>{total}</b>{name}</span>)}</div><div className="nestedCounts">{Object.entries(nestedCounts(data)).map(([name,total])=><span key={name}>{name.replace(/([A-Z])/g,' $1').trim()}: <b>{total}</b></span>)}</div><div className="replaceWarning"><AlertTriangle/><div><b>Your local data will remain untouched until cloud migration is verified.</b><span>Stable local IDs are used to prevent duplicates. Cloud counts and sample fields must match before cloud mode activates.</span></div></div>{!last&&<button className="ghost safetyBackup" onClick={exportNow}><Download/> Export Required Backup First</button>}{last&&<label className="migrationConsent"><input type="checkbox" checked={migrationConfirmed} onChange={event=>setMigrationConfirmed(event.target.checked)}/> I exported a backup and want to upload these records.</label>}<div className="modalActions"><button className="ghost" onClick={()=>setMigrationOpen(false)}>Cancel</button><button className="primary" disabled={!last||!migrationConfirmed||cloud.migrating} onClick={()=>void migrate()}>{cloud.migrating?'MIGRATING…':'MIGRATE TO CLOUD'}</button></div></div></div>}
  {pending&&<div className="scrim"><div className="modal backupConfirm"><div className="modalHead"><div><span className="eyebrow">VALID JST BACKUP</span><h2>RESTORE PREVIEW</h2></div><button className="icon" onClick={()=>setPending(null)}><X/></button></div><p>Backup created <b>{dateLabel(pending.exportedAt)}</b></p><div className="backupCounts">{Object.entries(counts(pending.data)).map(([name,total])=><span key={name}><b>{total}</b>{name}</span>)}</div><div className="replaceWarning"><AlertTriangle/><div><b>Replace current JST Command Center data with this backup?</b><span>{cloud.migrationComplete?'The restored records will be queued for shared cloud sync.':'Your current local data will be replaced in one operation.'}</span></div></div><button className="ghost safetyBackup" onClick={exportNow}><Download/> Download Current Backup First</button><div className="modalActions"><button className="ghost" onClick={()=>setPending(null)}>Cancel</button><button className="primary" onClick={restore}>Restore Backup</button></div></div></div>}
  {resetOpen&&<div className="scrim"><div className="modal resetConfirm"><div className="modalHead"><div><span className="eyebrow">{cloud.migrationComplete?'RELOAD DEVICE CACHE':'PERMANENT LOCAL RESET'}</span><h2>{cloud.migrationComplete?'RELOAD LOCAL CACHE':'RESET APP DATA'}</h2></div><button className="icon" onClick={()=>setResetOpen(false)}><X/></button></div><div className="replaceWarning"><AlertTriangle/><b>{cloud.migrationComplete?'Shared cloud records will not be deleted. This device will reload them after clearing its snapshot.':'This will permanently delete all locally stored JST Command Center data on this device.'}</b></div><label>Type <b>RESET</b> to continue<input autoFocus value={resetText} onChange={event=>setResetText(event.target.value)}/></label><div className="modalActions"><button className="ghost" onClick={()=>setResetOpen(false)}>Cancel</button><button className="dangerButton" disabled={resetText!=='RESET'} onClick={reset}>{cloud.migrationComplete?'Reload Cache':'Reset Everything'}</button></div></div></div>}
 </div>
}
